
# This is a CLI based quiz application.

import random
import time

TIME_LIMIT = 20  # seconds per question

# Questions with options (Generated by Google)
questions = [
    {
        "question": "What is the largest ocean on Earth?",
        "options": ["Pacific Ocean", "Indian Ocean", "Atlantic Ocean", "Arctic Ocean"],
        "answer": "Pacific Ocean"
    },
    {
        "question": "Which planet is known as the 'Red Planet'?",
        "options": ["Earth", "Mars", "Jupiter", "Saturn"],
        "answer": "Mars"
    },
    {
        "question": "Who wrote the Indian national anthem?",
        "options": ["Rabindranath Tagore", "Mahatma Gandhi", "Subhash Chandra Bose", "Jawaharlal Nehru"],
        "answer": "Rabindranath Tagore"
    },
    {
        "question": "What is the hardest natural substance on Earth?",
        "options": ["Gold", "Iron", "Diamond", "Silver"],
        "answer": "Diamond"
    },
    {
        "question": "Which continent is known as the 'Dark Continent'?",
        "options": ["Asia", "Africa", "Europe", "Australia"],
        "answer": "Africa"
    },
    {
        "question": "What is the capital of India?",
        "options": ["Mumbai", "New Delhi", "Chennai", "Kolkata"],
        "answer": "New Delhi"
    },
    {
        "question": "Which vitamin is produced when our skin is exposed to sunlight?",
        "options": ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"],
        "answer": "Vitamin D"
    },
    {
        "question": "Who invented the light bulb?",
        "options": ["Alexander Graham Bell", "Thomas Edison", "Isaac Newton", "Nikola Tesla"],
        "answer": "Thomas Edison"
    },
    {
        "question": "What is the longest river in the world?",
        "options": ["Amazon", "Yangtze", "Mississippi", "Nile"],
        "answer": "Nile"
    },
    {
        "question": "Which gas is most abundant in the Earth's atmosphere?",
        "options": ["Oxygen", "Carbon Dioxide", "Nitrogen (78%)", "Hydrogen"],
        "answer": "Nitrogen (78%)"
    },
    {
        "question": "Who is known as the 'Missile Man of India'?",
        "options": ["Dr. APJ Abdul Kalam", "Vikram Sarabhai", "Homi Bhabha", "C.V. Raman"],
        "answer": "Dr. APJ Abdul Kalam"
    },
    {
        "question": "How many continents are there on Earth?",
        "options": ["Five", "Six", "Seven", "Eight"],
        "answer": "Seven"
    },
    {
        "question": "Which country is known as the Land of the Rising Sun?",
        "options": ["China", "Japan", "Thailand", "South Korea"],
        "answer": "Japan"
    },
    {
        "question": "What is the chemical symbol for gold?",
        "options": ["Ag", "Au", "Gd", "Go"],
        "answer": "Au"
    },
    {
        "question": "In which year did India gain independence?",
        "options": ["1945", "1946", "1947", "1950"],
        "answer": "1947"
    }
]


def ask_ques(q):
    print("\n" + q["question"])

    options = q["options"][:]
    random.shuffle(options)

    for i, option in enumerate(options, 1):
        print(f"{i}. {option}")

    start_time = time.time()

    try:
        choice = int(input(f"\nEnter choice (1-4). You have {TIME_LIMIT} seconds: "))
    except:
        print("Invalid input!")
        return False

    end_time = time.time()

    if end_time - start_time > TIME_LIMIT:
        print("Time's up!")
        return False

    if 1 <= choice <= 4:
        if options[choice - 1] == q["answer"]:
            print("Correct!")
            return True
        else:
            print(f"Wrong! Correct answer: {q['answer']}")
            return False
    else:
        print("Invalid choice!")
        return False


def main():
    print("Welcome to the Quiz Game!")
    random.shuffle(questions)
    score = 0
    for q in questions:
        if ask_ques(q):
            score += 1

    print("\nQuiz Finished!")
    print(f"Your final score is: {score}/{len(questions)}") # i.e. final score --> 7/15


if __name__ == "__main__":
    main()